
package pe.edu.upeu.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FactorialIImplService", targetNamespace = "http://ws.upeu.edu.pe/", wsdlLocation = "http://localhost:2121/soap/factorial?wsdl")
public class FactorialIImplService
    extends Service
{

    private final static URL FACTORIALIIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FACTORIALIIMPLSERVICE_EXCEPTION;
    private final static QName FACTORIALIIMPLSERVICE_QNAME = new QName("http://ws.upeu.edu.pe/", "FactorialIImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:2121/soap/factorial?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FACTORIALIIMPLSERVICE_WSDL_LOCATION = url;
        FACTORIALIIMPLSERVICE_EXCEPTION = e;
    }

    public FactorialIImplService() {
        super(__getWsdlLocation(), FACTORIALIIMPLSERVICE_QNAME);
    }

    public FactorialIImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FACTORIALIIMPLSERVICE_QNAME, features);
    }

    public FactorialIImplService(URL wsdlLocation) {
        super(wsdlLocation, FACTORIALIIMPLSERVICE_QNAME);
    }

    public FactorialIImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FACTORIALIIMPLSERVICE_QNAME, features);
    }

    public FactorialIImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FactorialIImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FactorialDao
     */
    @WebEndpoint(name = "FactorialIImplPort")
    public FactorialDao getFactorialIImplPort() {
        return super.getPort(new QName("http://ws.upeu.edu.pe/", "FactorialIImplPort"), FactorialDao.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FactorialDao
     */
    @WebEndpoint(name = "FactorialIImplPort")
    public FactorialDao getFactorialIImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.upeu.edu.pe/", "FactorialIImplPort"), FactorialDao.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FACTORIALIIMPLSERVICE_EXCEPTION!= null) {
            throw FACTORIALIIMPLSERVICE_EXCEPTION;
        }
        return FACTORIALIIMPLSERVICE_WSDL_LOCATION;
    }

}
