
package pe.edu.upeu.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FactorialDao", targetNamespace = "http://ws.upeu.edu.pe/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FactorialDao {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calcularFactorial", targetNamespace = "http://ws.upeu.edu.pe/", className = "pe.edu.upeu.ws.CalcularFactorial")
    @ResponseWrapper(localName = "calcularFactorialResponse", targetNamespace = "http://ws.upeu.edu.pe/", className = "pe.edu.upeu.ws.CalcularFactorialResponse")
    @Action(input = "http://ws.upeu.edu.pe/FactorialDao/calcularFactorialRequest", output = "http://ws.upeu.edu.pe/FactorialDao/calcularFactorialResponse")
    public int calcularFactorial(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
